<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\ZenkeiViewer.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release' And '$(RuntimeIdentifier.StartsWith(`win`))' == 'true'">
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <OptimizationPreference>Size</OptimizationPreference>
    <AutoreleasePoolSupport>false</AutoreleasePoolSupport>
    <DebuggerSupport>false</DebuggerSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
    <EventSourceSupport>false</EventSourceSupport>
    <Http3Support>false</Http3Support>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <MetricsSupport>false</MetricsSupport>
    <StackTraceSupport>false</StackTraceSupport> 
    <XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Common.fs" />
    <Compile Include="DragMoveGestureRecognizer.fs" />
    <Compile Include="ExclusivePinchGestureRecognizer.fs" />
    <Compile Include="ImageViewControl.fs" />
    <AvaloniaXaml Include="ZenkeiViewerStyles.xaml" />
    <Compile Include="ZenkeiViewerStyles.xaml.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.FuncUI.Elmish" Version="1.5.2" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
    <PackageReference Include="Elmish" Version="5.0.2" />
    <PackageReference Include="FSharp.Collections.Immutable" Version="1.0.0" />
    <PackageReference Include="FSharp.Control.TaskSeq" Version="0.6.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="MetadataExtractor" Version="2.9.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="11.0.100" />
  </ItemGroup>
</Project>
